### PR TITLE
libfuzzer: fix false-positive memory leak in ikev2_msg

### LINKED ISSUE #35: Libfuzz-parser memory leaks
The Libfuzz-parser test reports a number of leaks in `ikev2_pld_parse()`:
```Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4cdf82 in calloc (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x4cdf82)
    #1 0x504747 in ibuf_open (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x504747)
    #2 0x50479d in ibuf_dynamic (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x50479d)
    #3 0x501b86 in ibuf_new (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x501b86)
    #4 0x5001c8 in ikev2_pld_delete (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x5001c8)
    #5 0x500e69 in ikev2_pld_payloads (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x500e69)
```
The reason is that the fuzzing harness does not call `ikev2_msg_cleanup()`. However, getting `ikev2_msg_cleanup()` to compile and link with the test is not trivial because of symbol conflicts with `common.c`.

### PR DESCRIPTION
**Pull request by linderd**
add a stub function in common.c to correctly free ikev2-msg in the libfuzzer-test.
this should fix #35

### CODE REVIEW

File: regress/parser-libfuzzer/test_parser_fuzz.c [hunk 1]
```diff
@@ -127,6 +127,7 @@ LLVMFuzzerTestOneInput(const char *Data, size_t Size)
 
 	ikev2_pld_parse(NULL, &hdr, &msg, 0);
 
-	ibuf_free(fuzzed);
+    ikev2_msg_cleanup(NULL, &msg);
```
Comment (tobhe) [inline regress/parser-libfuzzer/test_parser_fuzz.c:130]: tab

File: regress/parser-libfuzzer/common.c [hunk 2]
```diff
@@ -211,3 +212,42 @@ void
...
+                ibuf_release(cr->cr_data);
+                SIMPLEQ_REMOVE_HEAD(&msg->msg_certreqs, cr_entry);
+                free(cr);
+            }
+        }
+
+        if (msg->msg_data != NULL) {
+            ibuf_release(msg->msg_data);
+            msg->msg_data = NULL;
+        }
```
Comment (tobhe) [inline regress/parser-libfuzzer/common.c:252]: please use tabs for indentation

File: CMakeLists.txt [hunk 3]
```diff
@@ -341,7 +341,7 @@ add_subdirectory(iked)
 add_subdirectory(ikectl)
 add_subdirectory(regress/dh)
 add_subdirectory(regress/parser)
-if(CMAKE_SYSTEM_NAME MATCHES "Linux" AND CMAKE_C_COMPILER_ID STREQUAL "Clang")
```
Comment (tobhe) [inline CMakeLists.txt:344]: Why isn't this needed anymore? Isn't libfuzzer part of clang/llvm?

Comment (linderd) [reply CMakeLists.txt:344]: Libfuzzer is part of clang/llvm, but clang is not needed as compiler for the whole project.
Clang is defined as compiler only for parser-libfuzzer in regress/parser-libfuzzer/CMakeLists.txt:15

Comment (tobhe) [reply CMakeLists.txt:344]: Makes sense, but without this check the build will probably fail if llvm is not installed. What this check should actually do is see if clang + libfuzzer is installed on the system. The current check is not perfect but works because if you are compiling with clang then llvm + libfuzzer must be installed.

Comment (linderd) [reply CMakeLists.txt:344]: Ah, now I see the problem. Ok, I'll think of an option to check if clang/llvm is installed.

The problem with the old check is, that it is only true, if the default compiler is already clang, which is for example not the case on my fedora-machine.

**Review by tobhe — APPROVED** [review]
